# Generated by Django 4.2.5 on 2023-10-03 11:16

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alpha", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                error_messages={
                    "unique": "Пользователь с таким номером телефона уже существует"
                },
                help_text="Обязательное поле. Введите номер телефона без знака плюс (+), например: 998901234567",
                max_length=255,
                unique=True,
                validators=[
                    django.contrib.auth.validators.ASCIIUsernameValidator(
                        message="Значение должно состоять только из цифр",
                        regex="^[1-9][0-9]+$",
                    )
                ],
                verbose_name="номер телефона",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                error_messages={"unique": "Пользователь с таким именем уже существует"},
                help_text="Обязательное поле. Введите имя пользователя в Телеграме без собачки, например: my_username",
                max_length=32,
                unique=True,
                validators=[
                    django.contrib.auth.validators.ASCIIUsernameValidator(
                        message="Имя пользователя может содержать только заглавные (A-Z),     строчные (a-z) латинские буквы, цифры (0-9) и/или знак подчеркивания (_)",
                        regex="^[a-zA-Z0-9_]{5,32}$",
                    )
                ],
                verbose_name="Telegram-username",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={
                    "unique": "Пользователь с таким адресом электронной почты уже существует"
                },
                help_text="Обязательное поле. Введите адрес электронной почты, например: someone@example.com",
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "Пользователь с таким именем уже существует"},
                help_text="Обязательное поле. Введите имя пользователя в Телеграме без собачки, например: my_username",
                max_length=32,
                unique=True,
                validators=[
                    django.contrib.auth.validators.ASCIIUsernameValidator(
                        message="Имя пользователя может содержать только заглавные (A-Z),     строчные (a-z) латинские буквы, цифры (0-9) и/или знак подчеркивания (_)",
                        regex="^[a-zA-Z0-9_]{5,32}$",
                    )
                ],
                verbose_name="Telegram-username",
            ),
        ),
    ]
