# Generated by Django 4.2.6 on 2023-10-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alpha", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="receiving_address",
            field=models.ManyToManyField(
                blank=True,
                related_name="receiving_users",
                to="alpha.address",
                verbose_name="адрес доставки",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="sending_address",
            field=models.ManyToManyField(
                blank=True,
                related_name="sending_users",
                to="alpha.address",
                verbose_name="адрес отправки",
            ),
        ),
    ]
