# Generated by Django 4.2.6 on 2023-10-12 11:50

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alpha", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "Пользователь с таким именем уже существует"},
                help_text="Введите имя пользователя в Телеграме без собачки (@), например: my_username",
                max_length=255,
                unique=True,
                validators=[
                    django.contrib.auth.validators.ASCIIUsernameValidator(
                        message="Имя пользователя может содержать только заглавные (A-Z),     строчные (a-z) латинские буквы, цифры (0-9) и/или знак подчеркивания (_).     Длина имени пользователя должна быть от 5 до 32 символов.",
                        regex="^[a-zA-Z0-9_]{5,32}$",
                    )
                ],
                verbose_name="username",
            ),
        ),
    ]
