# Generated by Django 4.2.6 on 2023-10-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alpha", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="receiver_photo_1",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="delivery",
            name="sender_photo_1",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="delivery",
            name="sender_photo_2",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="delivery",
            name="sender_photo_3",
            field=models.BinaryField(null=True),
        ),
    ]
