# Generated by Django 4.2.5 on 2023-10-03 11:28

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("alpha", "0002_alter_customuser_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="receiving_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receiving_users",
                to="alpha.address",
                verbose_name="адрес доставки",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="sending_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sending_users",
                to="alpha.address",
                verbose_name="адрес отправки",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                error_messages={"unique": "Пользователь с таким именем уже существует"},
                help_text="Обязательное поле. Введите имя пользователя в Телеграме без собачки (@), например: my_username",
                max_length=32,
                unique=True,
                validators=[
                    django.contrib.auth.validators.ASCIIUsernameValidator(
                        message="Имя пользователя может содержать только заглавные (A-Z),     строчные (a-z) латинские буквы, цифры (0-9) и/или знак подчеркивания (_)",
                        regex="^[a-zA-Z0-9_]{5,32}$",
                    )
                ],
                verbose_name="Telegram-username",
            ),
        ),
        migrations.AlterField(
            model_name="truck",
            name="number",
            field=models.CharField(
                error_messages={"unique": "Такой самосвал уже cуществует"},
                max_length=255,
                unique=True,
                verbose_name="самосвал",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "Пользователь с таким именем уже существует"},
                help_text="Обязательное поле. Введите имя пользователя в Телеграме без собачки (@), например: my_username",
                max_length=32,
                unique=True,
                validators=[
                    django.contrib.auth.validators.ASCIIUsernameValidator(
                        message="Имя пользователя может содержать только заглавные (A-Z),     строчные (a-z) латинские буквы, цифры (0-9) и/или знак подчеркивания (_)",
                        regex="^[a-zA-Z0-9_]{5,32}$",
                    )
                ],
                verbose_name="Telegram-username",
            ),
        ),
    ]
