# Generated by Django 4.2.6 on 2023-10-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alpha", "0003_alter_customuser_receiving_address_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="receiving_address",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="sending_address",
        ),
        migrations.AddField(
            model_name="customuser",
            name="receiving_address",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="receiving_users",
                to="alpha.address",
                verbose_name="адрес доставки",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="sending_address",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="sending_users",
                to="alpha.address",
                verbose_name="адрес отправки",
            ),
        ),
    ]
