# Generated by Django 4.2.6 on 2023-10-27 02:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("alpha", "0003_delivery_receiver_photo_1_delivery_sender_photo_1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="delivery",
            old_name="receiver_photo_1",
            new_name="photo_1",
        ),
        migrations.RenameField(
            model_name="delivery",
            old_name="sender_photo_1",
            new_name="photo_2",
        ),
        migrations.RenameField(
            model_name="delivery",
            old_name="sender_photo_2",
            new_name="photo_3",
        ),
        migrations.RenameField(
            model_name="delivery",
            old_name="sender_photo_3",
            new_name="photo_4",
        ),
    ]
