# Generated by Django 4.2.6 on 2023-10-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alpha", "0004_rename_receiver_photo_1_delivery_photo_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="cargo_type",
            field=models.CharField(
                db_column="тип груза", max_length=255, verbose_name="тип груза"
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="receiver",
            field=models.CharField(
                db_column="получатель",
                max_length=255,
                null=True,
                verbose_name="получатель",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="receiver_address",
            field=models.CharField(
                db_column="адрес доставки",
                max_length=255,
                verbose_name="адрес доставки",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="sender",
            field=models.CharField(
                db_column="отправитель", max_length=255, verbose_name="отправитель"
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="sender_address",
            field=models.CharField(
                db_column="адрес отправки",
                max_length=255,
                verbose_name="адрес отправки",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="status",
            field=models.CharField(
                db_column="статус", max_length=255, verbose_name="статус"
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="transport_number",
            field=models.CharField(
                db_column="номер транспорта",
                max_length=255,
                verbose_name="номер транспорта",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="transport_type",
            field=models.CharField(
                db_column="тип транспорта",
                max_length=255,
                verbose_name="тип транспорта",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="weight",
            field=models.CharField(
                db_column="вес (кг)", max_length=255, verbose_name="вес (кг)"
            ),
        ),
    ]
