# Generated by Django 4.2.6 on 2023-10-07 10:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("alpha", "0004_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cargo",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="receiving_address",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="sending_address",
        ),
        migrations.DeleteModel(
            name="Delivery",
        ),
        migrations.DeleteModel(
            name="Truck",
        ),
        migrations.DeleteModel(
            name="Address",
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
