# Generated by Django 4.2.6 on 2023-10-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alpha", "0006_alter_delivery_cargo_type_alter_delivery_receiver_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="comment",
            field=models.TextField(null=True, verbose_name="комментарий"),
        ),
    ]
