# Generated by Django 4.2.6 on 2023-10-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alpha", "0007_delivery_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="truck",
            name="status",
            field=models.CharField(
                default="Свободен", max_length=255, verbose_name="статус"
            ),
        ),
    ]
